[theme]
base = "dark"
primaryColor = "#C6F432"
backgroundColor = "#0E0B16"
secondaryBackgroundColor = "#1A1428"
textColor = "#F2EEFA"
font = "sans-serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showSidebarNavigation = true
